# @package server

host: "0.0.0.0"
grpc_port: 50051
http_port: 8080
prometheus_port: 8000
# gRPC worker threads - should be >= 2x max experiment concurrency
# Auto-adjusted in main.py based on experiment.concurrency_levels
# Default increased to 16 to handle common concurrency levels
grpc_workers: 16
